# Generated by Django 3.2 on 2021-04-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
