# Generated by Django 3.2 on 2021-04-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210417_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('I', 'Investor'), ('B', 'Borrower')], max_length=2),
        ),
    ]
