# Generated by Django 3.2 on 2021-04-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210417_0133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
