# Generated by Django 3.2 on 2021-04-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='user_id',
            new_name='user',
        ),
    ]
